#!/usr/bin/bash
./configure --prefix=/usr \
            --localstatedir=/var/lib/vim \
            --with-features=huge \
            --with-compiledby="$(whoami)@$(hostname)" \
            --enable-gpm \
            --enable-acl \
            --with-x \
            --enable-gui \
            --enable-multibyte \
            --enable-cscope \
            --enable-netbeans \
            --enable-perlinterp=dynamic \
            --enable-pythoninterp=dynamic \
            --enable-python3interp=dynamic \
            --enable-rubyinterp=dynamic \
            --enable-luainterp=dynamic \
            --enable-tclinterp=dynamic \
            --enable-luainterp=yes \

sudo make && sudo make install
