#!/usr/bin/bash

# Tmux
cp ./.tmux.conf ~/.tmux.conf 
cp ./.tmux-theme.conf ~/.tmux-theme.conf

# Vim
cp ./.vimrc ~/.vimrc

# Keybinds
cp ./.xbindkeysrc ~/.xbindkeysrc

# UXvrt Terminal
cp ./.Xdefaults ~/.Xdefaults

# ZSH
cp ./.zshrc ~/.zshrc

# Rofi
sudo cp ./rofi-custom /usr/local/bin/rofi-custom 

# Openbox
cp ./openbox/rc.xml ~/.config/openbox/rc.xml
cp ./openbox/autostart ~/.config/openbox/autostart

# Tint 2
sudo cp ./tint2rc /usr/share/tint2/numix-customized-emil.tint2rc

# Wallpaper
sudo cp ./wallpaper.jpg /usr/share/backgrounds/wallpaper-emil.jpg
cp ./bg-saved.cfg ~/.config/nitrogen/bg-saved.cfg
