#!/usr/bin/bash

# Tmux
cp ./.tmux.conf ~/.tmux.conf 
cp ./.tmux-theme.conf ~/.tmux-theme.conf

# Vim
cp ./.vimrc ~/.vimrc

# Keybinds
cp ./.xbindkeysrc ~/.xbindkeysrc

# X Resources
cp ./.Xresources ~/.Xresources

# ZSH
cp ./.zshrc ~/.zshrc

# Openbox
cp ./openbox/rc.xml ~/.config/openbox/rc.xml
cp ./openbox/autostart ~/.config/openbox/autostart
sudo cp ./openbox/wmctrl-switch-by-application /usr/local/bin
sudo chmod +x /usr/local/bin/wmctrl-switch-by-application

# Tint 2
sudo cp ./tint2rc /usr/share/tint2/numix-customized-emil.tint2rc

# Wallpaper
sudo cp ./wallpaper.jpg /usr/share/backgrounds/wallpaper-emil.jpg
cp ./bg-saved.cfg ~/.config/nitrogen/bg-saved.cfg
