#!/usr/bin/bash

# Tmux
cp ~/.tmux.conf .
cp ~/.tmux-theme.conf .

# Vim
cp ~/.vimrc .

# Keybinds
cp ~/.xbindkeysrc .

# X Resources
cp ~/.Xresources .

# ZSH
cp ~/.zshrc .

# Openbox
cp ~/.config/openbox/rc.xml ./openbox
cp ~/.config/openbox/autostart ./openbox
cp /usr/local/bin/wmctrl-switch-by-application ./openbox/wmctrl-switch-by-application

# Tint 2
cp /usr/share/tint2/numix-customized-emil.tint2rc .

# Wallpaper
cp /usr/share/backgrounds/wallpaper-emil.jpg .
cp ~/.config/nitrogen/bg-saved.cfg .
