#!/usr/bin/bash

# Tmux
cp ~/.tmux.conf .
cp ~/.tmux-theme.conf .

# Vim
cp ~/.vimrc .

# Keybinds
cp ~/.xbindkeysrc .

# X Resources
cp ~/.Xresources .

# ZSH
cp ~/.zshrc .

# Ranger
cp ~/.config/ranger/commands.py ./ranger/commands.py

# Openbox
cp ~/.config/openbox/rc.xml ./openbox/rc.xml
cp ~/.config/openbox/autostart ./openbox/autostart
cp ~/.config/openbox/environment ./openbox/environment
cp ~/.config/openbox/menu.xml ./openbox/menu.xml
cp /usr/local/bin/wmctrl-switch-by-application ./openbox/wmctrl-switch-by-application

# Tint 2
cp /usr/share/tint2/numix-customized-emil.tint2rc .

# Wallpaper
cp /usr/share/backgrounds/wallpaper-emil.jpg ./wallpaper.jpg
cp ~/.config/nitrogen/bg-saved.cfg .

# Qutebrowser
cp ~/.config/qutebrowser/config.py ./qutebrowser/config.py
cp ~/.config/qutebrowser/config.yml ./qutebrowser/config.yml
