#!/usr/bin/bash
echo "Linux setup installer"

CDIR="$(pwd)"

repo_package_list=(
    # Reflector
    'reflector'

    # Core + Interpreters
    'zsh'
    'python'
    'perl'
    'lua'
    'ruby'
    'sudo'
    'gksu'
    'wget'
    'openssh'
    'sshfs'
    'dosfstools'
    'ntfs-3g'
    'parted'
    'acpi'
    'ntp'

    # Java
    'jre7-openjdk'
    'jdk7-openjdk'
    'jre8-openjdk'
    'jdk8-openjdk'
    'jre9-openjdk'
    'jdk9-openjdk'

    # Audio
    'pulseaudio'
    'pulseaudio-alsa'
    'alsa-utils'

    # Graphical
    'xorg-server'
    'qt4'
    'gtk2'
    'gtk3'
    'lightdm'
    'lightdm-gtk-greeter'
    'openbox'
    'nitrogen'
    'tint2'
    'xcompmgr'

    # Utilities
    'wmctrl'
    'pamixer'
    'rofi'
    'playerctl'
    'xbindkeys'
    'xorg-xprop'
    'xorg-xdpyinfo'
    'xsel'

    # Utility programs
    'obconf'
    'lxappearance'
    'xfce4-screenshooter'
    'htop' 
    'p7zip'
    'xorg-xinput'

    # Terminals
    'xterm'
    'rxvt-unicode'
    'tmux'

    # Editors
    'emacs'
    'leafpad'
    'retext'

    # Media and applications
    'steam'
    'vlc'
    'eog'
    'deluge'
    'thunar'
    'gimp'
    'inkscape'
    'teamspeak3'
    'evince'
    'audacity'
    'libreoffice'

    # Themes and fonts
    'adapta-gtk-theme'
    'terminus-font' 'ttf-hack' 'ttf-dejavu' 'noto-fonts' 'ttf-liberation' 'ttf-freefont'

    # Browsers + Mail clients
    'firefox'
    'chromium'
    'qutebrowser'
    'thunderbird'

    # Wine
    # 'wine' # Replace with wine-gaming-nine (AUR)
    # 'winetricks'
    # 'wine-mono'
    # 'wine_gecko'
)

aur_package_list=(
    # Graphical
    'conky-lua'

    # Themes and fonts
    'adwaita-qt4' 'adwaita-qt5'
    'la-capitaine-icon-theme'
    'ttf-ms-fonts' 'ttf-vista-fonts' 'ttf-google-fonts-git'

    # Media and applications
    'spotify'
    'pulseeffects'
    'discord'
    'p7zip-gui'

    # Wine + Gallium 9 (Compile time from outer space, install manually)
    # 'wine-gaming-nine'
)

gpgkeys=(
    '487EACC08557AD082088DABA1EB2638FF56C0C53'
    '11E521D646982372EB577A1F8F0871F202119294'
)

package_exists() {
    pacman -Q "$1" > /dev/null 2>&1
    return "$?"
}

install_keys() {
    echo "> Recieving GPG keys"
    for key in "${gpgkeys[@]}"; do
        gpg --recv-keys "$key"
    done
}

pacman_install() {
    if ! package_exists "$1"; then
        echo "> Installing official package $1..."
        sudo pacman -S --noconfirm "$1"

        if [[ "$?" == 0 ]]; then
            echo -e "\tSuccessfully installed $1!"
            return 0
        else
            echo -e "\tError! Could not install $1!"
            return 1
        fi
    else
        echo "$1 is already installed, skipping"
        return 0
    fi
}

pacaur_install() {
    if ! package_exists "$1"; then
        echo "> Installing AUR package $1..."
        pacaur -ya --noconfirm "$1"

        if [[ "$?" == 0 ]]; then
            echo -e "\tSuccessfully installed $1!"
            return 0
        else
            echo -e "\tError! Could not install $1!"
            return 1
        fi

        return "$?"
    else
        echo "$1 is already installed, skipping"
        return 0
    fi
}

aur_install() {
    echo "> Installing AUR package $1..."
    
    # Download
    curl -Lo package.tar.gz "https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz"
    mkdir "pkg-$1" && tar xvf package.tar.gz -C "pkg-$1" --strip-components 1
    cd "pkg-$1"

    # Compile and install
    makepkg
    sudo pacman -U --noconfirm *.tar.xz

    # Clean up
    cd ..
    rm -rf "pkg-$1"
}

install_vim() {
    local stopinstall=0

    echo "> Installing vim"

    # Remove any already existing vim
    if package_exists vim; then
        echo -e "\tVim already exists as a package, removing..."
        sudo pacman -Rd --noconfirm vim &> /dev/null
    elif [ -f /usr/bin/vim ]; then
        read -rp "/usr/bin/vim exists, continue installing vim [y/N]? " response

        if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
            stopinstall=0
        else
            stopinstall=1
        fi
    fi

    if [ $stopinstall == 0 ]; then
        # Download
        if [ -d vim ]; then
            rm -rf vim
        fi

        git clone https://github.com/vim/vim

        # Install
        if [ -d vim ]; then
            cd vim

            cp "$CDIR/scripts/build-vim" .  chmod +x build-vim
            ./build-vim

            rm -rf *
            cd ..
            rmdir vim
        fi
    fi
}

install_pacaur() {
    if ! package_exists pacaur; then
        echo "> Installing pacaur"
        pacman_install expac
        pacman_install yajl
        aur_install cower
        aur_install pacaur
    fi
}

install_packages() {
    echo "Installing packages..."
    pacman_install curl
    pacman_install git

    echo "Upgrading system..."
    sudo pacman -Syu --noconfirm &> /dev/null
    echo "Done!"

    if [ ! -d /tmp/linuxsetup ]; then
        mkdir /tmp/linuxsetup
    fi

    cd /tmp/linuxsetup

    # Pacaur
    if ! package_exists pacaur; then
        echo "> Installing pacaur"
        pacman_install expac
        pacman_install yajl
        aur_install cower
        aur_install pacaur
    fi

    # Vim
    install_vim

    # Repo packages
    for pkg in "${repo_package_list[@]}"; do
        pacman_install "$pkg"
        
        if [[ $? != 0 ]]; then
            echo "Package installation aborted due to error"
            return 1
        fi
    done

    # AUR packages
    for pkg in "${aur_package_list[@]}"; do
        pacaur_install "$pkg"

        if [[ $? != 0 ]]; then
            echo "Package installation aborted due to error"
            return 1
        fi
    done

    # Clean up
    rm -rf /tmp/linuxsetup
}

export_setup() {
    echo "Exporting setup..."

    # Export scripts
    for f in ./scripts/export/*; do
        echo "> Exporting $(basename $f) setup!"
        sh "$f"

        if [[ $? == 0 ]]; then
            echo "Successfully exported $(basename $f) setup!"
        else
            echo "Error! Could not export $(basename $f) setup!"
        fi
    done
}

import_setup() {
    echo "Importing setup..."

    # Export scripts
    for f in ./scripts/import/*; do
        echo "> Importing $(basename $f) setup!"
        bash "$f"

        if [[ $? == 0 ]]; then
            echo "Successfully imported $(basename $f) setup!"
        else
            echo "Error! Could not import $(basename $f) setup!"
        fi
    done
}

echo "What do you want to do?"
select choice in "Install GPG keys" "Install pacaur" "Install packages" "Export setup" "Import setup"
do
    case "$choice" in
        "Install GPG keys")
            install_keys
            break
            ;;
        "Install pacaur")
            install_pacaur
            break
            ;;
        "Install packages")
            install_packages
            break
            ;;
        "Export setup")
            export_setup
            break
            ;;
        "Import setup")
            import_setup
            break
            ;;
        *)
            exit 1
            ;;
    esac
done
