#!/usr/bin/bash
rofi -font hack\ 9 -combi-modi window,drun -show combi -color-window "#1d1f21, #1d1f21, #1d1f21" -color-normal "#1d1f21, #ffffff, #1d1f21, #cc6666, #1d1f21" -color-active "#1d1f21, #cc6666, #1d1f21, #cc6666, #1d1f21" -color-urgent "#1d1f21, #ffffff, #1d1f21, #ffffff, #1d1f21"
