#!/usr/bin/bash
echo "Copying lightdm greeter config..."

sudo mkdir -p /etc/lightdm
sudo cp ./contents/etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf

read -rp "Enable lightdm service [y/N]? " response

if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
    sudo systemctl enable lightdm.service
fi
