#!/usr/bin/bash
echo "Copying background file..."

sudo mkdir -p /usr/share/backgrounds
sudo cp ./contents/usr/share/backgrounds/wallpaper-emil.jpg /usr/share/backgrounds/wallpaper-emil.jpg

echo "Copying nitrogen settings..."

mkdir -p $HOME/.config/nitrogen
cp -r ./contents/home/.config/nitrogen/* $HOME/.config/nitrogen
