#!/usr/bin/bash
echo "Copying qutebrowser config..."

mkdir -p $HOME/.config/qutebrowser
cp -r ./contents/home/.config/qutebrowser/* $HOME/.config/qutebrowser

read -rp "Set qutebrowser as default web browser? [y/N]? " response

if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
    cd /usr/share/applications
    xdg-settings set default-web-browser qutebrowser.desktop
fi
