#!/usr/bin/bash
echo "Copying xdg settings..."

cd /usr/share/applications

xdg-settings set default-web-browser qutebrowser.desktop

# Common applications
xdg-mime default evince.desktop application/pdf
xdg-mime default gvim.desktop text/plain

# Video
xdg-mime default vlc.desktop video/3gpp
xdg-mime default vlc.desktop video/3gpp2
xdg-mime default vlc.desktop video/annodex
xdg-mime default vlc.desktop video/dv
xdg-mime default vlc.desktop video/isivideo
xdg-mime default vlc.desktop video/mj2
xdg-mime default vlc.desktop video/mlt-playlist
xdg-mime default vlc.desktop video/mp2t
xdg-mime default vlc.desktop video/mp4
xdg-mime default vlc.desktop video/mpeg
xdg-mime default vlc.desktop video/ogg
xdg-mime default vlc.desktop video/quicktime
xdg-mime default vlc.desktop video/vnd.mpegurl
xdg-mime default vlc.desktop video/vnd.rn-realvideo
xdg-mime default vlc.desktop video/vnd.vivo
xdg-mime default vlc.desktop video/wavelet
xdg-mime default vlc.desktop video/webm
xdg-mime default vlc.desktop video/x-anim
xdg-mime default vlc.desktop video/x-flic
xdg-mime default vlc.desktop video/x-flv
xdg-mime default vlc.desktop video/x-javafx
xdg-mime default vlc.desktop video/x-matroska
xdg-mime default vlc.desktop video/x-matroska-3d
xdg-mime default vlc.desktop video/x-mng
xdg-mime default vlc.desktop video/x-ms-wmp
xdg-mime default vlc.desktop video/x-ms-wmv
xdg-mime default vlc.desktop video/x-msvideo
xdg-mime default vlc.desktop video/x-nsv
xdg-mime default vlc.desktop video/x-ogm+ogg
xdg-mime default vlc.desktop video/x-sgi-movie
xdg-mime default vlc.desktop video/x-theora+ogg

# Image
xdg-mime default eog.desktop image/png
xdg-mime default eog.desktop image/jpeg
xdg-mime default eog.desktop image/gif
xdg-mime default eog.desktop image/bmp
xdg-mime default eog.desktop image/tiff

# Audio
xdg-mime default vlc.desktop audio/AMR
xdg-mime default vlc.desktop audio/AMR-WB
xdg-mime default vlc.desktop audio/aac
xdg-mime default vlc.desktop audio/ac3
xdg-mime default vlc.desktop audio/annodex
xdg-mime default vlc.desktop audio/basic
xdg-mime default vlc.desktop audio/flac
xdg-mime default vlc.desktop audio/midi
xdg-mime default vlc.desktop audio/mp2
xdg-mime default vlc.desktop audio/mp4
xdg-mime default vlc.desktop audio/mpeg
xdg-mime default vlc.desktop audio/ogg
xdg-mime default vlc.desktop audio/prs.sid
xdg-mime default vlc.desktop audio/vnd.dts
xdg-mime default vlc.desktop audio/vnd.dts.hd
xdg-mime default vlc.desktop audio/vnd.rn-realaudio
xdg-mime default vlc.desktop audio/webm
xdg-mime default vlc.desktop audio/x-adpcm
xdg-mime default vlc.desktop audio/x-aifc
xdg-mime default vlc.desktop audio/x-aiff
xdg-mime default vlc.desktop audio/x-amzxml
xdg-mime default vlc.desktop audio/x-ape
xdg-mime default vlc.desktop audio/x-flac+ogg
xdg-mime default vlc.desktop audio/x-gsm
xdg-mime default vlc.desktop audio/x-iriver-pla
xdg-mime default vlc.desktop audio/x-it
xdg-mime default vlc.desktop audio/x-m4b
xdg-mime default vlc.desktop audio/x-matroska
xdg-mime default vlc.desktop audio/x-minipsf
xdg-mime default vlc.desktop audio/x-mo3
xdg-mime default vlc.desktop audio/x-mod
xdg-mime default vlc.desktop audio/x-mpegurl
xdg-mime default vlc.desktop audio/x-ms-asx
xdg-mime default vlc.desktop audio/x-ms-wma
xdg-mime default vlc.desktop audio/x-musepack
xdg-mime default vlc.desktop audio/x-opus+ogg
xdg-mime default vlc.desktop audio/x-pn-audibleaudio
xdg-mime default vlc.desktop audio/x-pn-realaudio-plugin
xdg-mime default vlc.desktop audio/x-psf
xdg-mime default vlc.desktop audio/x-psflib
xdg-mime default vlc.desktop audio/x-riff
xdg-mime default vlc.desktop audio/x-s3m
xdg-mime default vlc.desktop audio/x-scpls
xdg-mime default vlc.desktop audio/x-speex
xdg-mime default vlc.desktop audio/x-speex+ogg
xdg-mime default vlc.desktop audio/x-stm
xdg-mime default vlc.desktop audio/x-tta
xdg-mime default vlc.desktop audio/x-voc
xdg-mime default vlc.desktop audio/x-vorbis+ogg
xdg-mime default vlc.desktop audio/x-wav
xdg-mime default vlc.desktop audio/x-wavpack
xdg-mime default vlc.desktop audio/x-wavpack-correction
xdg-mime default vlc.desktop audio/x-xi
xdg-mime default vlc.desktop audio/x-xm
xdg-mime default vlc.desktop audio/x-xmf
xdg-mime default vlc.desktop x-content/audio-cdda
xdg-mime default vlc.desktop x-content/audio-dvd
xdg-mime default vlc.desktop x-content/audio-player

# Office
xdg-mime default libreoffice-writer.desktop application/msword
xdg-mime default libreoffice-writer.desktop application/msword
xdg-mime default libreoffice-writer.desktop application/vnd.openxmlformats-officedocument.wordprocessingml.document

xdg-mime default libreoffice-calc.desktop application/vnd.ms-excel

xdg-mime default libreoffice-impress.desktop application/vnd.ms-powerpoint
xdg-mime default libreoffice-impress.desktop application/vnd.openxmlformats-officedocument.presentationml.presentation

# Archives
xdg-mime default 7zFM.desktop application/zip
xdg-mime default 7zFM.desktop application/x-rar-compressed
xdg-mime default 7zFM.desktop application/x-7z-compressed
