#!/usr/bin/bash
echo "Copying zshrc..."

cp ./contents/home/.zshrc $HOME/.zshrc

if [ ! -d $HOME/.oh-my-zsh ]; then
    echo "Installing oh-my-zsh..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

shbin="$(getent passwd $LOGNAME | cut -d: -f7)"

if [ ! $shbin == "$(which zsh)" ]; then
    read -rp "Change shell to zsh [y/N]? " response

    if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
        chsh -s "$(which zsh)"
    fi
fi
