#!/usr/bin/bash

#####################
#    Base setup     #
#####################

# Xcompmgr
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &

# Xbindkeys
xbindkeys &

# Nitrogen
nitrogen --restore &

# Tint 2
tint2 &

# Conky
conky -d

# PulseEffects
pulseeffects --gapplication-service &

#####################
# Startup programs  #
#####################

steam &
spotify &
