#!/usr/bin/bash

#####################
#    Base setup     #
#####################

# Fix nvidia display
nvidia-fix &

# Xbindkeys
xbindkeys &

# Nitrogen
nitrogen --restore &

# Tint 2
tint2 &

# Compton
compton -bcC &

#####################
# Startup programs  #
#####################

steam &
spotify &
pulseeffects &
